### ISSUE TITLE
Code of conduct

### ISSUE THREAD

**Issue by onli** [s9y/s9y.github.io#14]
The current docs navigation proposes to have a codex under http://docs.s9y.org/docs/contributing/codex.html that would still need to be written.

**Comment by yellowled** [comment]
I think that was supposed to contain kind of a hands-on “How to contribute”. Something like your typical “use 4 spaces to indent, use iso-8859-1 for these files and utf-8 only for those etc." – it's probably not a good name for it since we already have the Code Primer which is similar.

Also, we should probably find out how to use drafts in Jekyll in order to not publish those unfinished pages. (We'll have to remove them from the nav manually, though.)

**Comment by onli** [comment]
Ah. I thought it was a behavioral codex, about being nice to the other? Otherwise I agree that the Code primer might cover this.

Maybe it would be enough to just not link to drafts, as long as we have an issue for the item so it won't be forgotten.

**Comment by yellowled** [comment]
I'm not entirely sure what it was intended for, but it was not a code of conduct. Quite frankly, I don't think we'll need something like that.

**Comment by onli** [comment]
It was indeed a code of conduct! Added in https://github.com/s9y/s9y.github.io/commit/d40e65eb3273ce2ab834bc0c39eecd5a63a7138a

**Comment by garvinhicking** [comment]
Waiting for feedback of @ophian - when accepted and our page is live, we should add our link to the list of adopters of covenant

**Comment by yellowled** [comment]
Are we _still_ waiting on feedback 3 months later or why is this still open?

**Comment by onli** [comment]
Yeah. I think we don't need this issue anymore. The code is on the website and was accepted by at least the majority of the team. I'll close here, re-open if needed (i.e. if we really want a list of adopters, but I don't think that's needed).
