### ISSUE TITLE
Feature list

### ISSUE THREAD

**Issue by onli** [s9y/s9y.github.io#18]
We have a feature list under http://docs.s9y.org/features.html that is based on the old website, minus the comparing section. That list could profit from a better presentation and maybe also feature selection.

**Comment by onli** [comment]
Future plans: adding icons to the blocks. Try it out whether the themes block could have a thumbnail of an image showing two or more very different themes.

Comments and suggestions welcome.

**Comment by yellowled** [comment]
I don't think this is very readable. It is very little text per section, which makes for a lot of heading with barely a line of text in the paragraph following it. I don't think this works unless _every_ section contains at least as much text as “Dynamic”, and even then, it might be hard to scan for the eye because the lines are too short.

**Comment by onli** [comment]
Probably looks different to you than to me. _edit:_ Thanks for the feedback!

Some sections could still be combined . On the other hand, supporting users skimming through over the page with big headlines listing the feature is a lot better than the list we had before. 

But this was a first try, and is not done yet. You have an alternative approach?

**Comment by yellowled** [comment]
Readability and scanability because of short line lengths is not really something that is subjective. I also don't think that this is easy to skim. It does not “lead” the eye very well because of the short lines and the columns.

My suggestion would be to first go back to the “full width layout” and to rewrite the text first, trying to make the paragraphs inbetween the headings into actual paragraphs (as in “more than a sentence”).

I keep wondering why you keep using these grid layouts for text. It might be that the docs need a shorter line length in general (either by making the container less wide or by increasing the font size). Or, you know, you just really like columns.

**Comment by onli** [comment]
Yeah, it might be too much currently. I understand the impression that it does not lead the eye well.

> My suggestion would be to first go back to the “full width layout” and to rewrite the text first, trying to make the paragraphs inbetween the headings into actual paragraphs (as in “more than a sentence”).

I don't think that's the solution either. That would be fully a wall of text.

I'll describe why I re-used the columns: I wanted to have a structure. Starting point was one wide and long list of text. I don't think that this is a good format: [Users don't read](https://www.nngroup.com/articles/how-users-read-on-the-web/), the features should be presented skimmable and not just be described. Having them as distinguishable blocks is a first step in that direction. The important part of that page are the headlines, not the description texts – and the headlines replace and fortify the bolded parts of http://www.s9y.org/3.html.

This also explains why I combined the columns with images at the front page proposal. Would love to have that here as well, one image for every block showing the features, bigger though. Hard for some of them, what image would describe BSD more clearly? Idea: divide them; a section at the top with images and one full width list below with what remains.

But maybe that needs a totally different approach, or maybe each feature block should look different, have a different structure.

**Comment by yellowled** [comment]
> I understand the impression that it does not lead the eye well.

It is not an _impression_, though.

> Having them as distinguishable blocks

But the blocks are not distinguishable because they look very much alike and thus merge into a pattern.

> But maybe that needs a totally different approach

I think the best idea would be to first get the content of the page (close to) finalized so that you can work with actual content. I know you want to get this done asap, but it does not make sense to hurry it for the sake of gettting it finished. Also: try combining the _long_ lines (ie. without columns) with images to reduce the actual line length. Images in columns will not work.

**Comment by onli** [comment]
As long as you haven't done a user study it is an impression ;)

I'll play with it a bit. Not set in stone and stuff.

**Comment by onli** [comment]
So. I don't know. Think it could work. Added some more margin, some images and think currently it would be at least an improvement to what is there now.

If there is no better solution presented, I would in the future:
1. Add two or four images more, re-grouping the list so they are side by side.
2. Make the short texts a bit longer
3. Combine the section Standards Compliant, PHP-Powered, Open Source and Actively maintained in a full width footer that might be normal text.

But I'll give it some time. Might even be me who suggests another solution in the meantime.

**Comment by onli** [comment]
Hm. I tried to do that but got stuck with the css, but by now I don't really remember anymore what the problem was. @yellowled, do you want to go over it, or did you come up with an alternative approach? Otherwise I'd like to close here and let it like it is.

**Comment by yellowled** [comment]
I'll do some minor CSS stuff (margins etc.) and close it. I don't really have a better approach at the moment and I don't think it's worth stalling the website release any longer.
