### ISSUE TITLE
Activate this as new homepage

### ISSUE THREAD

**Issue by onli** [s9y/s9y.github.io#34]
In my eyes we are ready, and we should activate this site as our new site now.

The blog and spartacus design could follow later, or be finished when we know this page will go live. The forum design will work – improvable of course, but I'm certain it will hold up.

@garvinhicking, can you make the switch?

**Comment by garvinhicking** [comment]
Sure, didnt check up on the state of this due to workload. I can turn it on after my holidays in the second week of september!

**Comment by yellowled** [comment]
> The blog and spartacus design could follow later, or be finished when we know this page will go live. 

The blog theme is close to finished. Well, not _actually_ finished but close to a state that could go live. Meaning there are some minor details that I could probably fix until mid September and some things that could be adapted later or that I'd need to see in the live context anyway.

As for Spartacus, I haven't had a chance to emerge it locally yet, which is why I haven't even started developing the spartacus theme. But I think we could well change Spartacus later.

**Comment by yellowled** [comment]
> As for Spartacus, I haven't had a chance to emerge it locally yet

I now opted to create static HTML files to develop the Spartacus theme, which works fairly well. Should not be that hard to port to the emerge files, those do actually not emit that much markup anyway (most of it is done in `homepage/index.php`).

**Comment by yellowled** [comment]
Done.
