### ISSUE TITLE
Navigation does not work properly

### ISSUE THREAD

**Issue by mariohommel** [s9y/s9y.github.io#40]
In Main-Navigation the link "Plugins" lead to the spartacus "homepage", not to the plugin section. The link "Themes" leads to the templates section of spartacus but the "Plugins" link is highlighted.

**Comment by yellowled** [comment]
There is no proper way to link to the plugin section on Spartacus because it's split in event and sidebar plugins. There simply is no common view that lists _all_ plugins. I still think it's a good idea to link to plugins and themes seperately, though.

I have no idea if it is possible to change the highlighted menu item for themes on spartacus, that's a bit over my head PHP-wise. But that should indeed be fixed, if possible.

**Comment by yellowled** [comment]
Off the top of my head, I would think this should work (in `homepage/index.php`), but maybe @garvinhicking can take a look at it before I commit it?

``` php
<?php if (($_REQUEST['mode']) == 'template_all') { ?>
<li><a href="index.php">Plugins</a></li>
<li id="current-page"><a href="index.php?mode=template_all">Themes</a></li>
<?php } else { ?>
<li id="current-page"><a href="index.php">Plugins</a></li>
<li><a href="index.php?mode=template_all">Themes</a></li>
<?php } ?>
```
